### ISSUE TITLE
The user [...] wasn't found.

### ISSUE THREAD

**Issue by lukehatfield** [vinkla/instagram#59]
All of a sudden I'm getting a user not found error. I don't know of any site updates that would have effected this. How can I troubleshoot? I've tried putting in various Instagram users and I get the same error.

**Comment by Hervie** [comment]
same here.. seems that Instagram has closed media page, ie: [https://www.instagram.com/jerryseinfeld/media/](url) so it returns 404..

**Comment by nucreativa** [comment]
same here... idk why instagram close media page without any notice :(

**Comment by lupka** [comment]
Same issue here. Crazy that this would just disappear.

**Comment by vinkla** [comment]
I think @Hervie is right. It seems they have removed the option to fetch the Instagram feed as JSON. If anyone find any other solution to fetch the data, please let us know! I'll do some research as well.

**Comment by vinkla** [comment]
I think I've a simple solution which would require a small rewrite:

1. [Generate an access token](http://instagram.pixelunion.net) for the profile you want to be able to access.
2. Add the access token to a new Instagram instance.
3. Fetch the user data by the users ID.

What do you think? Simple enough?

**Comment by mserralta** [comment]
I have tested the solution you propose and it is simple and effective. It works.

I can do PR if you want

**Comment by mserralta** [comment]
I did PR if helps

**Comment by blu94** [comment]
Same here, still no solution?

**Comment by vinkla** [comment]
> Same here, still no solution?

This is an open-source project. It has been 12 hours since Instagram removed the endpoint.

**Comment by vinkla** [comment]
I've released version [8.0.0](https://github.com/vinkla/instagram/releases/tag/8.0.0) with the access token solution ✨

**Comment by hervie** [comment]
thanks for updating this!

**Comment by BrunoMCTeixeira** [comment]
for me it still doesn't work

$instagram = new Instagram('TOKEN');
$feedPhotos = $instagram->get('USERNAME');

Type error: Argument 1 passed to Vinkla\Instagram\Instagram::__construct() must be an instance of Http\Client\HttpClient or null, string given

**Comment by vinkla** [comment]
@BrunoMCTeixeira looks like you're using an older version. Upgrade to version 8.0.0.

**Comment by MarcosMe** [comment]
Hello Vinkla,
Not clear to me, can I fetch public users media with this new version? Or only my media? I'm using latest version 8.0.0 but can only access my own media with $instagram->get('publicUserId'). BTW this was working in previous version (before Instagram changes).

**Comment by vinkla** [comment]
@MarcosMe please read the installation guide.

**Comment by MarcosMe** [comment]
@vinkla You mean this Note:
Note: You can only fetch a user's recent media from the given access token.

**Comment by vinkla** [comment]
@MarcosMe no, the entire installation process. You can only fetch media from the user's account associated with the access token.

**Comment by MarcosMe** [comment]
Ok, so, it is no longer possible to access public profiles media with this package, correct?

**Comment by vinkla** [comment]
@MarcosMe no, didn't you read the comments in this thread?

**Comment by MarcosMe** [comment]
@vinkla I read it, more than once :) but still don't understand how to get the public profiles media with this change. Do I need to create an access token for the public profile?

**Comment by vinkla** [comment]
Yes, you need to create an access token.

**Comment by MarcosMe** [comment]
But how to create an access token for a public profile (not my profile, which I already created the token and it works)?

**Comment by MarcosMe** [comment]
Or do I need to use my profile access token and get the public profile (not mine) media using public profile  user ID?

**Comment by vinkla** [comment]
> But how to create an access token for a public profile (not my profile, which I already created the token and it works)?

You can't.

> Or do I need to use my profile access token and get the public profile (not mine) media using public profile user ID?

You can only use the access token for the user you generated the access token with.

**Comment by MarcosMe** [comment]
@vinkla I believe there was some miscommunication here, sorry if I'm not being clearer.
> Ok, so, it is no longer possible to access public profiles media with this package, correct?

> @MarcosMe no, didn't you read the comments in this thread?

Your "no" answer was to the "correct?" question, or to confirm "no, this is not possible anymore"?

**Comment by vinkla** [comment]
@MarcosMe no, this is not possible anymore.

**Comment by MarcosMe** [comment]
@vinkla Clear now, thank you.
